properties:
  resources:
    - resource: Microsoft.Windows.Developer/Taskbar
      directives:
        description: Modify taskbar settings
        allowPrerelease: true
      settings:
        Alignment: Left # [KeepCurrentValue, Middle]
        HideLabelsMode: Always # [KeepCurrentValue, WhenFull, Always]
        SearchBoxMode: ShowIconOnly # [KeepCurrentValue, ShowIconOnly, SearchBox, Hide]
        TaskViewButton: Show # [KeepCurrentValue, Hide]
        WidgetsButton: Show # [KeepCurrentValue, Hide]
        RestartExplorer: True # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required for `HideLabelsMode`.
    - resource: Microsoft.Windows.Developer/WindowsExplorer
      directives:
        description: Modify Windows Explorer settings
        allowPrerelease: true
      settings:
        FileExtensions: Show # [KeepCurrentValue, Hide]
        HiddenFiles: Hide # [KeepCurrentValue, Hide]
        ItemCheckBoxes: Hide # [KeepCurrentValue, Hide]
        RestartExplorer: True # Use caution when setting `RestartExplorer: true` as this will force explorer to close. Required for all WindowsExplorer settings.
    - resource: Microsoft.Windows.Developer/ShowSecondsInClock
      directives:
        description: Show seconds in clock
        allowPrerelease: true
      settings:
        Ensure: Present    
  configurationVersion: 0.2.0